environment: development
container:
  name: hello-gin
  port: 8080
  image: impacteintr/hellocloud
  tag: v1.4
  memory: "20Mi"
  cpu: "250m"
  livenessProbe:
    path: /healthz
    port: 8080
    initialDelaySeconds: 3
    periodSeconds: 3
replicas: 3
