apiVersion: v1
kind: LimitRange
metadata:
  name: demo-limitrange
spec:
  limits:
    - default:
        cpu: {{ .Values.limitrange.default.cpu }}
        memory: {{ .Values.limitrange.default.memory }}
      defaultRequest:
        cpu: "200m"
        memory: "128Mi"
      type: Container
